apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: postech-soat1-app
          image: monicahillman/postech-soat1-app:latest
          ports:
            - containerPort: 8080
