version: '3'

networks:
  my-network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=padoca
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 2s
      retries: 10
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network